### ISSUE TITLE
🚀New Feature Request - For a fully functional and understandable webpage

### ISSUE THREAD

**Issue by amriths04** [Altreus/colourblind#6]
🚀 Feature Request

📝 Description
Instead of viewers just experimenting with different types of color blindness, We could instead find their type , help them analyze other types too.

✨ Describe the solution you'd like
I believe that it makes sense to emulate as much as possible the real behaviour of such web pages.
My suggestion is to allow the user to define what is the preferred . 

✍️ Tasks:
I've not seen so far one such website where users get to understand their type along with taking their test.

1. Try an alternative to the famous Ishihara test(if possible).
2. Attractive piece of information for all types of color blindness.

**Comment by anvitha1633** [comment]
Can I take task 1?

**Comment by anvitha1633** [comment]
@amrith00025 , Since there wasn't any reply from the owners , I think i can just give a try?
![Screenshot (286)](https://user-images.githubusercontent.com/72348110/130229431-2a617631-f5cc-4ea1-8123-60cf41bb97dd.png)
This tells users what their blindness type is . I'll add type number too. Along with this ,I'll add some effects from Bootstrap 4 which is the newest version of Bootstrap, and is the most popular HTML, CSS, and JavaScript framework for developing responsive, mobile-first websites...., due to which viewers would successfully remain at our web page even longer!!!!!!!!

**Please review and let me know what you think!**

**Comment by amriths04** [comment]
Yah Looks great to me , So  @anvitha1633  could add :

- [x] add some effects when tapped on the image ....
- [x] Since a new webpage is added, a navbar would be nice....

**Comment by amriths04** [comment]
I went through the PR @anvitha1633 . This was actually much more of contributions than what I had thought before coming up with this issue !! XD
ThankYou
